-- Creation of the database crud_project

CREATE DATABASE crud_project CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE crud_project;

-- Creation of the clients table

CREATE TABLE clients (
   id_client INT AUTO_INCREMENT,
   firstname VARCHAR(50) NOT NULL,
   name VARCHAR(50) NOT NULL,
   email VARCHAR(100) NOT NULL,
   phone VARCHAR(20) NOT NULL,
   address VARCHAR(255) NOT NULL,
   PRIMARY KEY (id_client),
   UNIQUE (email),
   UNIQUE (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Insert sample data generated by ChatGPT

INSERT INTO clients (firstname, name, email, phone, address)
VALUES
   ('Alice', 'Dupont', 'alice.dupont@example.com', '+33612345678', '123 Rue de Paris, 75001 Paris'),
   ('Bob', 'Martin', 'bob.martin@example.com', '+33623456789', '456 Avenue des Champs, 75008 Paris'),
   ('Clara', 'Durand', 'clara.durand@example.com', '+33634567890', '789 Boulevard Haussmann, 75009 Paris'),
   ('David', 'Lemoine', 'david.lemoine@example.com', '+33645678901', '321 Rue Saint-Honoré, 75001 Paris'),
   ('Emma', 'Rousseau', 'emma.rousseau@example.com', '+33656789012', '654 Place Vendôme, 75002 Paris'),
   ('Fabien', 'Morel', 'fabien.morel@example.com', '+33667890123', '987 Rue de Rivoli, 75004 Paris'),
   ('Gisèle', 'Benoit', 'gisele.benoit@example.com', '+33678901234', '135 Quai Voltaire, 75007 Paris'),
   ('Hugo', 'Perret', 'hugo.perret@example.com', '+33689012345', '246 Rue Lafayette, 75010 Paris'),
   ('Isabelle', 'Fontaine', 'isabelle.fontaine@example.com', '+33690123456', '357 Rue Saint-Michel, 75005 Paris'),
   ('Julien', 'Blanc', 'julien.blanc@example.com', '+33601234567', '468 Rue de Rennes, 75006 Paris');
